version: '3'
services:
  db:
    image: mysql
    container_name: aspire-app-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=aspire
  aspire-loan-app:
    image: aspire-loan-app
    container_name: aspire-loan-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=user:password@tcp(aspire-app-db:3306)/aspire
      - MIGRATION_PATH=/db_setup.sql
